# Generated by Django 4.2.11 on 2024-07-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profilePic",
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
