# Generated by Django 4.2.11 on 2024-06-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
