# Generated by Django 4.2.11 on 2024-06-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="position",
            field=models.CharField(
                choices=[
                    ("MB", "Member"),
                    ("CR", "Core"),
                    ("JS", "Joint Secretary"),
                    ("FS", "Finance Secretary"),
                    ("GS", "General Secretary"),
                ],
                default="MB",
                max_length=20,
            ),
        ),
    ]
