# Generated by Django 4.2.11 on 2024-05-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_remove_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="position",
            field=models.CharField(
                choices=[
                    ("MB", "Member"),
                    ("CR", "Core"),
                    ("JS", "Joint Secretary"),
                    ("FS", "Finance Secretary"),
                    ("GS", "General Secretary"),
                ],
                default="MB",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
