# Generated by Django 4.2.11 on 2024-06-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_customuser_is_admin_customuser_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
