# Generated by Django 4.2.11 on 2024-06-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0004_alter_customuser_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_member",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
