version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: merchstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  api:
    build: .
    command: >
      sh -c "
      python /app/backend/manage.py collectstatic --noinput &&
      python /app/backend/manage.py migrate &&
      gunicorn backend.wsgi:application --bind 0.0.0.0:3376
      "
    volumes:
      - .:/app
      - ./static/:/app/static/
      - ./logs/:/app/logs/
      - ./media/:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: merchstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data: