# Generated by Django 4.2.11 on 2024-07-04 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percentage', models.FloatField()),
                ('max_uses', models.IntegerField()),
                ('expiry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom', models.BooleanField(default=False)),
                ('uses', models.IntegerField(default=0)),
                ('roles_allowed', models.ManyToManyField(blank=True, related_name='discount_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
